name: Pytest Testing Suite
'on':
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - review_requested
      - synchronize
  push:
    branches:
      - main
  workflow_call:

jobs:
  units:
    name: Unitary Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Access test directory
        run: cd tests
        working-directory: tests
      - name: Run unit tests
        run: pytest test_units.py

  endpoints:
    name: Endpoint Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start Flask app
        run: python app.py &
      - name: Wait for app to start
        run: sleep 5
      - name: Access test directory
        run: cd tests
        working-directory: tests
      - name: Run endpoint tests
        run: pytest endpoints.py
      - name: Stop Flask app
        run: pkill -f "python app.py" || true